SUPABASE_URL = "https://zatvtgyymxvtlshrulzj.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphdHZ0Z3l5bXh2dGxzaHJ1bHpqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1ODU0OTc0NSwiZXhwIjoyMDc0MTI1NzQ1fQ.BqWsr1qQOlpsyFIddS98OuKPkmC7uIlwekWUzljFOwo"
SMTP_HOST = "smtpauths.bluewin.ch"
SMTP_PORT = "465"
SMTP_USERNAME = "philippethevoz@bluewin.ch"
BLUEWIN_SMTP_PASSWORD = "Ca+An=2316/Pippa&Tessa"
SENDER_EMAIL = "philippethevoz@bluewin.ch"
SENDER_NAME = "PHT Team"
SMTP_STARTTLS = "false"
SMTP_SSL = "true"