SUPABASE_URL = "https://zatvtgyymxvtlshrulzj.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphdHZ0Z3l5bXh2dGxzaHJ1bHpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NDk3NDUsImV4cCI6MjA3NDEyNTc0NX0.xvTNAr7Ui5vLYsXb8Mt28jiCSG27wOV56v5SB41T5-Q"
